"""initial migration

Revision ID: 9c9ba0209a49
Revises: 
Create Date: 2023-12-20 08:27:24.251213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9ba0209a49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('characterId', sa.Integer(), nullable=False),
    sa.Column('characterName', sa.String(), nullable=True),
    sa.Column('playerId', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('characterId')
    )
    op.create_table('players',
    sa.Column('playerId', sa.Integer(), nullable=False),
    sa.Column('playerName', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('playerId')
    )
    op.create_table('transactions',
    sa.Column('transactionId', sa.Integer(), nullable=False),
    sa.Column('characterId', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(precision=2), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('transactionDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('transactionId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('players')
    op.drop_table('characters')
    # ### end Alembic commands ###
